# Use postgres/example user/password credentials
version: '3.1'

services:

  mydbhostname:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: Password1
      POSTGRES_USER: phetho
      POSTGRES_DB: pythondb
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080