services:
  restapi:
    build: rest-api
    depends_on:
      - db
    links:
      - db
    ports:
    - 5000:5000
  web:
    build: nginx
    ports:
    - "80:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users
      POSTGRES_USER: rest
    ports:
    - 5432:5432