services:
  restapi:
    build: rest-api
    depends_on:
      - db
  web:
    build: nginx
    ports:
    - "80:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      POSTGRES_USER: root
    ports:
    - 5432:5432